### ISSUE TITLE
Component PLM-EPD-INS needs to be replaced with PLM-CLOUD-INS

### ISSUE THREAD

**Issue by gregorwolf** [SAP-docs/btp-build-work-zone-advanced#14]
### Issue description

Hello Build WZ Team,

when searching for the component PLM-EPD-INS at https://me.sap.com/mynotes?tab=Search I get the hint:

![image](https://github.com/user-attachments/assets/3d78c0f1-73ac-4be1-b3f9-4c88a9f2d2da)

So it seems that a replacement with PLM-CLOUD-INS is needed.

Best regards,
Gregor

### Feedback Type (Optional)

outdated information

### Page Title on SAP Help Portal (prefilled)

Getting Support

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/build-work-zone-advanced-edition/sap-build-work-zone-advanced-edition/getting-support?locale=en-US

**Comment by AnatKoren** [comment]
Thank you, Gregor.
This will be fixed in the next release.

**Comment by gregorwolf** [comment]
12545
