### ISSUE TITLE
Feedback for "Add or Update Context"

### ISSUE THREAD

**Issue by piejanssens** [SAP-docs/btp-build-work-zone-advanced#4]
https://help.sap.com/docs/WZ/7d3b9c7211ca4d7a9630b524205ee836/e69aef3fb6f448d084ce601ebf4555da.html?locale=en-US

"Card Actions" is a link to an SAP intranet page.

**Comment by AnatKoren** [comment]
Thank you for your input.
We will correct this.

**Comment by je-hal** [comment]
@AnatKoren : This issue has been open for 88 days. If the issue is fixed, please add the `contribution` label and close it.
